name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Buildozer dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache git libncurses5:i386 libstdc++6:i386 zlib1g:i386 openjdk-8-jdk unzip ant

    - name: Install Buildozer
      run: pip install --user buildozer

    - name: Build APK
      run: buildozer -v android debug
