name: Build APK

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the Python version compatible with Kivy and Buildozer

    - name: Install dependencies
      run: |
        sudo apt-get install -y \
          python3-dev \
          gcc \
          build-essential \
          git \
          libssl-dev \
          libffi-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          pkg-config \
          python3-setuptools \
          wget \
          && sudo apt-get clean

        python -m pip install --upgrade pip
        pip install buildozer

    - name: Build APK
      run: |
        buildozer init
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: ./bin/*.apk
